image: node:latest

stages: # Lista dos stages para os jobs e a sua ordem de execução
  - install
  - test
  - build
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build-job:
  stage: build
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - out/

test-job: # Apenas inicia quando o job build stage é concluido com sucesso
  stage: test # todos os testes abaixo run em paralelo
  script:
    - npm run lint
    - npm run prettier
    - npm run test
  cache:
    paths:
      - node_modules/

deploy:
  stage: deploy
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
