name: CI/CD Pipeline

on:
  push:
    branches:
    - main
    - alteracoes

jobs:
  secret_key_step:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Secrets API Key
      run: |


      env:
        API_KEY: ${{ secrets.API_KEY }}
  lint:
    needs: secret_key_step
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm install
    - name: Run Lint
      run: npm run lint

  
  check-merges:
    runs-on: ubuntu-latest
    needs: lint
    steps:
       - name: Check for Pending Merges
         uses: actions/checkout@v2
         with:
          ref: main
       - name: Verifica alterações caso a verificação de erros de codigo tenha passado
         run: |
            if [[ ${{ needs.lint.result }} == 'success' ]]; then
            if git log alteracoes..HEAD; then
                 echo "Existem alterações a serem feitas caso queiras fazer deves fazer manualmente"
                else
                 echo "Não existem alterações a serem feitas"
                fi
            fi
